### ISSUE TITLE
build requires cmake >= 3.7

### ISSUE THREAD

**Issue by erantapaa** [kimwalisch/primecount#15]
Building under Ubuntu 16.04 with `cmake` version 3.5.1 yielded the error:

```
   if given arguments:

     "CMAKE_VERSION" "VERSION_GREATER_EQUAL" "3.9"

   Unknown arguments specified
```

According to this thread:

https://github.com/Dav1dde/glad/issues/134

`VERSION_GREATER_EQUAL` is only supported in versions 3.7 or later.

Suggest altering the minimum required version of cmake to `cmake_minimum_required(VERSION 3.7)`.

**Comment by kimwalisch** [comment]
Thanks for letting me know.

My primesieve and primesum projects are also affected by this bug. I don't want to increase the minimum cmake version to 3.7 though because then people on older Linux distros (e.g. ubuntu 16.04) cannot easily build my projects.

According to the link you posted I can use ```if (NOT CMAKE_VERSION VERSION_LESS 3.9)``` instead of ```VERSION_GREATER_EQUAL 3.9``` because VERSION_LESS seems to be supported since [CMake 3.0](https://cmake.org/cmake/help/v3.0/command/if.html).

**Comment by kimwalisch** [comment]
Fixed by https://github.com/kimwalisch/primecount/commit/e8c4d748c9f630e752197b4ed50e852d1022d47c
