### ISSUE TITLE
Legendre O(x)

### ISSUE THREAD

**Issue by flcoder** [kimwalisch/primecount#16]
Please forgive me since I'm not great at figuring out these formulas, but
your table says that pi_legendre solves 10^11 in .03 seconds, but the comments in pi_legendre say:

/// Count the number of primes <= x using Legendre's formula.
/// Run time: O(x)
/// Memory usage: O(x^(1/2))

I may not be interpreting O() correctly, but I would assume O(x) means x operations.  If I write a program that just iterates to 10^11, it takes a long time, many seconds.  Is this because I am misinterpreting how O() works or is it because my program is single threaded and slower than the computer used to produce the results in the table?

Thanks in advance!

Will

**Comment by jwood000** [comment]
Your interpretation of Big O is incorrect. Run time complexity of a **specific algorithm** is only concerned with time in response to the size of its input at infinity.  The bolded text is to emphasize that when talking about Big O, we can only compare run times of an algorithm with itself, so your argument about comparing the run time of `primecount` with a program that iterates `10^11` times is not correct.  A typical example you see for linear time complexity, or `O(x)`, would be something like:

```
F(100) -->> time 20 seconds
F(1000) -->>  time 200 seconds
F(10000) -->>  time 2000 seconds
```

That is, the input increased by a factor of 10, and the run time for `F` increased by a factor of 10. In practice, one does not often see such clean responses. It should also be noted that I haven't shown you any details about `F`, but we can loosely say that its run-time complexity is linear.

My point is, `O(x)` does not mean `x` operations. It simply means that the run time grows linearly as the size of `x` increases.

**Comment by kimwalisch** [comment]
Hi,

All PrimePi formulas implemented in primecount make heavy use of caching and use precomputed lookup tables to speed things up. This means that for small input values the run time is often much faster than what you would expect from the Big-O notation. But for large enough input values the Big-O notation should make more sense (because caching does not improve the overall run-time complexity).

With a Big-O notation of O(n) the run time of ```func(n*10)``` should be roughly 10x larger than the run time of ```func(n)``` for large enough values of n. If you look at the benchmark timings for ```pi_legendre(x)``` below you see that ```pi_legendre(10^18)``` takes about 10x longer to compute than ```pi_legendre(10^17)```. Hence ```pi_legendre(x)``` has indeed a run-time complexity of O(x).

<table>
  <tr align="center">
    <td><b>x</b></td>
    <td><b>Prime Count</b></td>
    <td><b>Legendre</b></td>
    <td><b>Meissel</b></td>
    <td><b>Lagarias<br/>Miller<br/>Odlyzko</b></td>
    <td><b>Deleglise<br/>Rivat</b></td>
  </tr>
  <tr align="right">
    <td>10<sup>10</sup></td>
    <td>455,052,511</td>
    <td>0.02s</td>
    <td>0.01s</td>
    <td>0.01s</td>
    <td>0.01s</td>
  </tr>
  <tr align="right">
    <td>10<sup>11</sup></td>
    <td>4,118,054,813</td>
    <td>0.03s</td>
    <td>0.02s</td>
    <td>0.01s</td>
    <td>0.01s</td>
  </tr>
  <tr align="right">
    <td>10<sup>12</sup></td>
    <td>37,607,912,018</td>
    <td>0.10s</td>
    <td>0.06s</td>
    <td>0.03s</td>
    <td>0.02s</td>
  </tr>
  <tr align="right">
    <td>10<sup>13</sup></td>
    <td>346,065,536,839</td>
    <td>0.46s</td>
    <td>0.26s</td>
    <td>0.06s</td>
    <td>0.04s</td>
  </tr>
  <tr align="right">
    <td>10<sup>14</sup></td>
    <td>3,204,941,750,802</td>
    <td>2.66s</td>
    <td>1.28s</td>
    <td>0.19s</td>
    <td>0.10s</td>
  </tr>
  <tr align="right">
    <td>10<sup>15</sup></td>
    <td>29,844,570,422,669</td>
    <td>17.51s</td>
    <td>7.65s</td>
    <td>0.73s</td>
    <td>0.35s</td>
  </tr>
  <tr align="right">
    <td>10<sup>16</sup></td>
    <td>279,238,341,033,925</td>
    <td>136.16s</td>
    <td>55.30s</td>
    <td>2.95s</td>
    <td>1.26s</td>
  </tr>
  <tr align="right">
    <td>10<sup>17</sup></td>
    <td>2,623,557,157,654,233</td>
    <td>1,155.34s</td>
    <td>456.08s</td>
    <td>12.49s</td>
    <td>4.57s</td>
  </tr>
  <tr align="right">
    <td>10<sup>18</sup></td>
    <td>24,739,954,287,740,860</td>
    <td>10,239.22s</td>
    <td>3,974.21s</td>
    <td>55.87s</td>
    <td>18.97s</td>
  </tr>
  <tr align="right">
    <td>10<sup>19</sup></td>
    <td>234,057,667,276,344,607</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>86.13s</td>
  </tr>
  <tr align="right">
    <td>10<sup>20</sup></td>
    <td>2,220,819,602,560,918,840</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>373.09s</td>
  </tr>
  <tr align="right">
    <td>10<sup>21</sup></td>
    <td>21,127,269,486,018,731,928</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>1,747.57s</td>
  </tr>
  <tr align="right">
    <td>10<sup>22</sup></td>
    <td>201,467,286,689,315,906,290</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>NaN</td>
    <td>8,215.59s</td>
  </tr>
</table>

The benchmarks above were run on an AMD Ryzen 7 1700 CPU (8 x 3.0
GHz, 3.7 GHz Turbo) from 2017 and primecount was compiled using
GCC 6.3.

**Comment by flcoder** [comment]
Wow, that makes a LOT of sense now.  Thank you both for taking the time to explain that to me!
