### ISSUE TITLE
Question regarding PhiTiny test

### ISSUE THREAD

**Issue by JakubDrozd** [kimwalisch/primecount#50]
https://github.com/kimwalisch/primecount/blob/49b286f5df9cb011496add39a23ef3c9bd670e92/test/phi_tiny.cpp#L54
@kimwalisch 
Could you explain this line to me, please? I mean a step-by-step explanation of all the pieces of the line. And another thing: could you set up discussions, so I wouldn't need to open issues, please? I would really appreciate.

**Comment by JakubDrozd** [comment]
@kimwalisch could you explain this?

**Comment by JakubDrozd** [comment]
@kimwalisch could you explain this, please?

**Comment by kimwalisch** [comment]
This is a sieve of Eratosthenes **byte sieve** array, all bytes are initialized to 1. The other day we talked about PhiTiny::sieve_ which is a sieve of Eratosthenes **bit sieve** array, all bits are initialized to 1. Bit sieving is a technique to reduce the memory usage of the sieve array so that it better fits in the CPU's cache.

Read up on the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes) to acquire more knowledge...

**Comment by JakubDrozd** [comment]
Ok. And one bonus: you can contribute to my implementation! Just follow the link: https://github.com/JakubDrozd/JSprimecount/invitations

**Comment by JakubDrozd** [comment]
@kimwalisch And could you set up discussions, so I wouldn't need to open issues?
