### ISSUE TITLE
Reason for nth prime limit?

### ISSUE THREAD

**Issue by JoshuaRLi-Savioke** [kimwalisch/primecount#9]
Hey! Thanks for making `primecount`, it's amazingly fast. Just curious about one thing--is there any particular reason as to why 216289611853439384 was chosen as a [limit](https://github.com/kimwalisch/primecount/blob/master/src/nth_prime.cpp#L24)?

EDIT: Whoops, meant to comment as JoshuaRLi, not my work account, no biggie though :P

**Comment by kimwalisch** [comment]
> is there any particular reason as to why 216289611853439384 was chosen as a limit?

For the nth_prime() algorithm, the final step requires use of a prime sieve. I use my own [primesieve](https://github.com/kimwalisch/primesieve) library for this, but primesieve can only generate primes < 2^64. For primecount I have further more decided to use signed integers in the API, that's why the limit of the  nth_prime() algorithm is 216289611853439384, 216289611853439384 is the number of primes <= 2^63 (if I remember correctly).

It would probably be easy to make the nth_prime() algorithm work for 128-bit integers using an external library, but one of my design goals is not to rely on any external library in order to make primecount extremely portable and easy to build.

I will investigate how much code would be required to make nth_prime() work with 128-bit integers.

**Comment by JoshuaRLi** [comment]
Okay, thanks for the explanation--makes sense!
